enum LEVEL_EVENTS {
  TILE_OVER = "TILE_OVER",
  TILE_OUT = "TILE_OUT",
  TILE_SELECT_PRIMARY = "TILE_SELECT_PRIMARY",
  TILE_SELECT_SECONDARY = "TILE_SELECT_SECONDARY",
  EXIT_OVER = "EXIT_OVER",
  EXIT_OUT = "EXIT_OUT",
  EXIT_SELECT_PRIMARY = "EXIT_SELECT_PRIMARY"
}

export default LEVEL_EVENTS;
