enum LEVEL_EVENTS {
  TILE_OVER = "TILE_OVER",
  TILE_OUT = "TILE_OUT",
  TILE_SELECT_PRIMARY = "TILE_SELECT_PRIMARY",
  TILE_SELECT_SECONDARY = "TILE_SELECT_SECONDARY"
}

export default LEVEL_EVENTS;
