enum TILE_TYPES {
  ENTRANCE = "ENTRANCE",
  EXIT = "EXIT",
  BLANK = "BLANK",
  ENEMY = "ENEMY",
  SCRAMBLE_ENEMY = "SCRAMBLE_ENEMY",
  SHIELD_CONTROL = "SHIELD_CONTROL",
  GOLD = "GOLD",
  SHOP = "SHOP",
  WALL = "WALL",
  KEY = "KEY"
}

export default TILE_TYPES;
